/*
 * Created: 2014-12-10
 * 
 * ====================================================================
 *    The author of this file licenses it to you under the Apache
 *    License, Version 2.0. You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing,
 *    software distributed under the License is distributed on an
 *    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *    KIND, either express or implied.  See the License for the
 *    specific language governing permissions and limitations
 *    under the License.
 * ====================================================================
 */
package at.co.malli.relpm.gui;


/**
 * @author Dietmar Malli
 */
public class AboutDialog extends javax.swing.JDialog
{

  /**
   * Creates new form AboutDialog
   */
  public AboutDialog (java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();
    setLocationRelativeTo(null);
  }


  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jPanNorth = new javax.swing.JPanel();
    jLalIcon = new javax.swing.JLabel();
    jLabVersion = new javax.swing.JLabel();
    jPanCenter = new javax.swing.JPanel();
    jScroll = new javax.swing.JScrollPane();
    jTAabout = new javax.swing.JTextArea();
    jPanSouth = new javax.swing.JPanel();
    jButClose = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("About");
    setMinimumSize(new java.awt.Dimension(420, 550));
    setPreferredSize(new java.awt.Dimension(420, 550));
    setResizable(false);

    jPanNorth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

    jLalIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/co/malli/relpm/gui/icons/RelPM/RelPM_64x64.png"))); // NOI18N
    jPanNorth.add(jLalIcon);

    jLabVersion.setText("Version: 1.1");
    jPanNorth.add(jLabVersion);

    getContentPane().add(jPanNorth, java.awt.BorderLayout.NORTH);

    jPanCenter.setLayout(new java.awt.BorderLayout());

    jScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

    jTAabout.setEditable(false);
    jTAabout.setLineWrap(true);
    jTAabout.setText("This tool is completely open source. If you would like to\ncontribute in development, found a bug, have got a great idea or a feature request you can contact Dietmar Malli (Didi1357) on GitHub or just patch it yourself:\n\n    https://github.com/didi1357/relpm/\n\nContributions of any kind are always welcome.\n\nMost of the code is licensed under the Apache License, Version 2.0. You may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n \nUnless required by applicable law or agreed to in writing, software distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the License for the specific language governing permissions and limitations under the License.");
    jTAabout.setWrapStyleWord(true);
    jTAabout.setFocusable(false);
    jTAabout.setRequestFocusEnabled(false);
    jScroll.setViewportView(jTAabout);

    jPanCenter.add(jScroll, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanCenter, java.awt.BorderLayout.CENTER);

    jButClose.setText("Close");
    jButClose.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButCloseActionPerformed(evt);
      }
    });
    jPanSouth.add(jButClose);

    getContentPane().add(jPanSouth, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButCloseActionPerformed
  {//GEN-HEADEREND:event_jButCloseActionPerformed
    dispose();
  }//GEN-LAST:event_jButCloseActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main (String args[])
  {
    /*
     * Set the Nimbus look and feel
     */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /*
     * Create and display the dialog
     */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run ()
      {
        AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter()
        {
          @Override
          public void windowClosing (java.awt.event.WindowEvent e)
          {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButClose;
  private javax.swing.JLabel jLabVersion;
  private javax.swing.JLabel jLalIcon;
  private javax.swing.JPanel jPanCenter;
  private javax.swing.JPanel jPanNorth;
  private javax.swing.JPanel jPanSouth;
  private javax.swing.JScrollPane jScroll;
  private javax.swing.JTextArea jTAabout;
  // End of variables declaration//GEN-END:variables

}
